### ISSUE TITLE
Make CLI support all relevant model types

### ISSUE THREAD

**Issue by kmaziarz** [microsoft/molecule-generation#13]
Currently all CLI entry points only work for `MoLeRVae` as they use `VaeWrapper`, while e.g. `molecule_generation sample` could also support `MoLeRGenerator`. While generalizing things, we may also want to rethink the choice to do model type discovery based on filenames (@sarahnlewis may have thoughts on this).

**Comment by anamika-yadav99** [comment]
Hi @kmaziarz I'm an undergrad student from India. I do have experience working on similiar projects and CLI. Can I work on this issue?

**Comment by sarahnlewis** [comment]
@kmaziarz  is your suggestion that the model type be found in the contents of the same `.pkl` file that `get_model_parameters` reads, or that we save a separate file e.g. `model_type.txt` with each trained model? I think I would prefer the latter.

**Comment by kmaziarz** [comment]
> @kmaziarz is your suggestion that the model type be found in the contents of the same .pkl file that get_model_parameters reads, or that we save a separate file e.g. model_type.txt with each trained model?

The model class is already being saved in the `*.pkl` file (which is a `dict`, containing not only the model class and weights but also various other hyperparams), and `load_vae_model_and_dataset` (the lower level model loading utility used for all model types) use the class it reads to load the model. So my proposal is to just make use of that (which has an advantage of being compatible with old checkpoints out-of-the-box).

**Comment by sarahnlewis** [comment]
OK, sounds good.

**Comment by anamika-yadav99** [comment]
Thanks for the head start @kmaziarz  and @sarahnlewis . I'll get started with the task.

**Comment by anamika-yadav99** [comment]
Hi @kmaziarz  so far I have been able to extract the model class from the .pkl file and defined a method which returns which model wrapper class to use based on the model class i.e. Vaewrapper for `MoLeRVae` and GeneratorWrapper for `MoLeRGenerator` class. Now the confusion that I have is that GeneratorWrapper doesn't have encode method. From the sample function already defined, it looks like GeneratorWrapper doesn't need one.  Should I add a method similar to VaeWrapper or just return the sample_latents?

**Comment by kmaziarz** [comment]
> Now the confusion that I have is that GeneratorWrapper doesn't have encode method. From the sample function already defined, it looks like GeneratorWrapper doesn't need one. Should I add a method similar to VaeWrapper or just return the sample_latents?

`GeneratorWrapper` should not have `encode`, as it represents latent-space-less models that can only sample (that's why it needs to be a separate class, because the API is more limited). Anywhere `encode` is called (e.g. `cli/encode.py`) we should keep using the `VaeWrapper`, while e.g. in `cli/sample.py` we can use the generic `load_model_from_directory`.
