### ISSUE TITLE
Sample molecules based on a specific scaffold

### ISSUE THREAD

**Issue by cesc-fabregas2020** [microsoft/molecule-generation#22]
Thanks for this excellent work !

In the README inference part, "molecule_generation encode MODEL_DIR SMILES_PATH OUTPUT_PATH" is used to generate molecules. How can I sample molecules based on a specific scaffold?

Looking forward to your reply

**Comment by kmaziarz** [comment]
> In the README inference part, "molecule_generation encode MODEL_DIR SMILES_PATH OUTPUT_PATH" is used to generate molecules.

So `encode` is for encoding into the latent space (converting molecules into vectors of real numbers), while `sample` and `decode` do some actual generation (with only the former being exposed through the CLI at the moment).

> How can I sample molecules based on a specific scaffold?

This isn't exposed in the CLI interface (which is mostly designed for very simple things for now), and so I would recommend to load the model from Python following the code snipped in the "Inference" section of the README. The `decode` method has a `scaffolds` argument ([see here](https://github.com/microsoft/molecule-generation/blob/5cdcd74838c6c61e6fa2e72770ea66ddede384ee/molecule_generation/wrapper.py#L112)) that you can use. You also need to provide a latent code to decode; for a simple demonstration, you can take an encoding of a molecule containing that scaffold and perturb it slightly to get similar scaffold-constrained samples.

Quick example:
```python
import numpy as np
from molecule_generation import VaeWrapper

model_dir = "./example_model_directory"
scaffold = "C1=CC=CC=C1"
init_mol = "O=CNC1=CC=CC=C1"

with VaeWrapper(model_dir) as model:
    [latent_center] = model.encode([init_mol])
    latents = latent_center + 0.5 * np.random.randn(10, latent_center.shape[0]).astype(np.float32)

    for idx, smiles in enumerate(model.decode(latents, scaffolds=[scaffold] * len(latents))):
        print(f"Result #{idx + 1}: {smiles}")
```
prints
```
Result #1: NC(=O)C1=CC=CC=C1
Result #2: O=CNC1=CC=CC=C1
Result #3: CC(=NNC1=CC=CC=C1)C(N)=O
Result #4: CC(=O)NC1=CC=C(C(N)=O)C=C1
Result #5: NC(=O)C1=CC=CC=C1N
Result #6: NC1=CC=C(C(=O)NC2=CC=CC=C2)C=C1
Result #7: O=CNC1=CC=CC=C1
Result #8: O=C(NC1=CC=CC=C1)C1=CC=CC=C1
Result #9: NC(=O)C1=CC=C(NC=O)C=C1
Result #10: O=CNC1=CC=CC=C1[N+](=O)[O-]
```
