### ISSUE TITLE
M1 Mac problem

### ISSUE THREAD

**Issue by MKCarter** [microsoft/molecule-generation#31]
Hi,
I am trying to run the command 

`molecule_generation sample MODEL_DIR 10`

On my M1 mac, trying this with the current install instructions leads to the following error:

`zsh: illegal hardware instruction  molecule_generation sample MODEL_DIR 10`

Do you know any fix for this?

Thanks,
Mike

**Comment by MKCarter** [comment]
OK, I have a fix for this. For M1 Macs you need to install Tensorflow from the source - 
e.g. one of these https://drive.google.com/drive/folders/11cACNiynhi45br1aW3ub5oQ6SrDEQx4p
Now it works as expected, I think...
```
molecule_generation sample MODEL_DIR 10  
Loading a trained model from: MODEL_DIR/GNN_Edge_MLP_MoLeR__2022-02-24_07-16-23_best.pkl
2022-08-31 12:03:19,747 trace_dataset.py:44 INFO Initialising TraceDataset.
2022-08-31 12:03:19,748 trace_dataset.py:44 INFO Initialising TraceDataset.
2022-08-31 12:03:19,756 trace_dataset.py:44 INFO Initialising TraceDataset.
2022-08-31 12:03:19,764 trace_dataset.py:44 INFO Initialising TraceDataset.
2022-08-31 12:03:19,767 trace_dataset.py:44 INFO Initialising TraceDataset.
2022-08-31 12:03:19,775 trace_dataset.py:44 INFO Initialising TraceDataset.
O=C1C2=CC=C(C3=CC=CC=C3)C=C=C2OC2=CC=CC=C12
CC(=O)NC1=NC2=CC(OCC3=CC=CN(CC4=CC=C(Cl)C=C4)C3=O)=CC=C2N1
CCN1C(=O)C2=CC=CC=C2N=C1NC(C)C(=O)NCC(=O)N=[N+]=[N-]
CC(=O)N1CCCC1C1=NC2=CC=C(C(C)(C)CCCC(C)C)C=C2NC1=NC1=CC=C(O)C=C1
N=C(N)NCCCCOC1=CC=C(Br)C(Cl)=N1
O=C1C2=CC=C(C3=NN=CO3)C=C2N=CN1CC1=CC=C(C2=CC=CC=C2)C=C1
O=CCCCCCN1C=CC2=CC=CC=C21
CCOC(=O)C1=CC2=CC(CC(C)C)=CC=C2N=C1C1=CC=C(Br)C=C1
CC1=C(C#N)C=C(NC(=O)NC2CCCCC2)N1CC#N
CC1=CNN=C1NC(=O)COC1=CC=C(Cl)C=C1Cl
```

**Comment by kmaziarz** [comment]
Hey @MKCarter - indeed, `tensorflow` installation may differ on macs, and the output you got looks right (in fact, I'm getting exactly same molecules on Linux, so it's good that things are deterministic across platforms). I will mention this discrepancy in the README.
