### ISSUE TITLE
Pre-training model download link failed

### ISSUE THREAD

**Issue by lonngxiang** [microsoft/molecule-generation#38]
![image](https://user-images.githubusercontent.com/40717349/201574773-ca3e646e-9cd5-48e5-bdd6-ff10e1f83c67.png)

**Comment by kmaziarz** [comment]
I'm not sure how to debug this because the link still works on my end. Can you maybe try a different machine or web browser?

**Comment by lonngxiang** [comment]
> I'm not sure how to debug this because the link still works on my end. Can you maybe try a different machine or web browser?

ok，but i still not work；please Add an alternate download site if possible

**Comment by kmaziarz** [comment]
I checked with my colleagues in China (as this is what you have set as your location) and indeed the link doesn't work for them, so it's a location-specific issue. If you have access to a VPN that would likely fix things, but I can also provide an alternative download link. Do you have suggestions of something that would work in China?

**Comment by lonngxiang** [comment]
> I checked with my colleagues in China (as this is what you have set as your location) and indeed the link doesn't work for them, so it's a location-specific issue. If you have access to a VPN that would likely fix things, but I can also provide an alternative download link. Do you have suggestions of something that would work in China?

Thank you for your reply,  can you upload to Baidu Cloud Disk or Google Cloud Disk or huggingface

**Comment by kmaziarz** [comment]
Does [this Baidu Cloud link](https://pan.baidu.com/s/1lkiWK9-d5MvNyzqRrusGXA?pwd=4hij) work?

**Comment by lonngxiang** [comment]
> Does [this Baidu Cloud link](https://pan.baidu.com/s/1lkiWK9-d5MvNyzqRrusGXA?pwd=4hij) work?

yep，it works， tks
