### ISSUE TITLE
How does decode can return multiple similar molecules？

### ISSUE THREAD

**Issue by lonngxiang** [microsoft/molecule-generation#40]

**Comment by lonngxiang** [comment]
also How do you extract similar molecules from LATENT SPACE NEIGHBORHOOD？

**Comment by kmaziarz** [comment]
If you want to get several molecules similar to a given seed molecule `m`, you can encode it, perturb its embedding by random noise, and then decode back. If the noise is too small, you'll get many copies of `m` back, while if it's too large, the molecules won't be that similar; if you tune the noise magnitude just right you'll get "neighbors" of `m`. You can see Appendix F in the [arxiv version of the paper](https://arxiv.org/abs/2103.03864) for more details.

Does that answer your question?
