### ISSUE TITLE
Question about node_type_predictor_class_loss_weight_factor

### ISSUE THREAD

**Issue by HiokHian** [microsoft/molecule-generation#45]
Hi,

In this line, it seems that there is a mention of a `node_type_predictor_class_loss_weight_factor` from the metadata, but I couldn't seem to find where this was generated in the preprocessing script and it also didn't seem to appear after running the preprocessing script. Could I check if this attribute has been deprecated and is no longer being used in this repo? Or did I miss something in the preprocessing steps? Thanks!

**Comment by kmaziarz** [comment]
This hyperparameter controls loss weighing for the next node prediction steps. It interpolates between the standard uniform weighing, and weighing which is inversely proportional to the frequency (which we store as `train_next_node_type_distribution`); the idea was to downweigh very common next node types (e.g. carbon).

We experimented with this briefly, but didn't see a significant effect from it, so by default (and in the models trained for all of our experiments), `node_type_predictor_class_loss_weight_factor` is not set (which is equivalent to setting it to `0.0`, i.e. uniform weighing). I wouldn't call it deprecated, in the sense that if you set it, it should hopefully still work, but there's no way of setting it from the CLI.

**Comment by HiokHian** [comment]
I see, thanks for the clarification!
