### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by ZhouChenghui** [microsoft/molecule-generation#48]
Hello, after I preprocessed the data and run train as described in the documentation, I immediately get the following error during data loading. Do you guys have any insight into why it happens? Thank you!

Traceback (most recent call last):
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/bin/molecule_generation", line 8, in <module>
    sys.exit(main())
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/cli/cli.py", line 35, in main
    run_and_debug(lambda: commands[args.command].run_from_args(args), getattr(args, "debug", False))
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/dpu_utils/utils/debughelper.py", line 21, in run_and_debug
    func()
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/cli/cli.py", line 35, in <lambda>
    run_and_debug(lambda: commands[args.command].run_from_args(args), getattr(args, "debug", False))
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/cli/train.py", line 140, in run_from_args
    loaded_model_dataset = training_utils.get_model_and_dataset(
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/tf2_gnn/cli_utils/model_utils.py", line 299, in get_model_and_dataset
    model = get_model(
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/tf2_gnn/cli_utils/model_utils.py", line 224, in get_model
    return model_cls(
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/models/moler_vae.py", line 89, in __init__
    super().__init__(params, dataset, **kwargs)
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/models/moler_base_model.py", line 60, in __init__
    super().__init__(params, dataset, **kwargs)
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/tf2_gnn/models/graph_task_model.py", line 55, in __init__
    batch_description = dataset.get_batch_tf_data_description()
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/dataset/trace_dataset.py", line 376, in get_batch_tf_data_description
    base_description = super().get_batch_tf_data_description()
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/tf2_gnn/data/graph_dataset.py", line 259, in get_batch_tf_data_description
    "node_features": (None,) + self.node_feature_shape,
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/dataset/trace_dataset.py", line 517, in node_feature_shape
    return self._get_cached_property("_node_feature_shape")
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/dataset/trace_dataset.py", line 510, in _get_cached_property
    self._load_feature_shapes_from_data()
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/dataset/trace_dataset.py", line 500, in _load_feature_shapes_from_data
    datum = self._load_one_sample(data_fold)
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/dataset/jsonl_abstract_trace_dataset.py", line 108, in _load_one_sample
    return next(iter(graph_it))
  File "/zfsauton2/home/chenghuz/miniconda3/envs/moler-env/lib/python3.9/site-packages/molecule_generation/utils/sharded_data_reader.py", line 92, in __next__
    next_datum = self._current_file_data.pop()
IndexError: pop from empty list

**Comment by kmaziarz** [comment]
I'm not sure what happened; it looks like the iterator that is supposed to return all graphs in the preprocessed dataset was empty. Was the preprocessing successful, did it create some output files? Can you post some logs from the preprocessing step?

**Comment by ZhouChenghui** [comment]
The preprocessing created output files, during the preprocessing, the output log looks either like this:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
2023-02-10 19:39:59,375 data_conversion_utils.py:231 WARNING Unable to convert GraphSample(adjacency_list=[Edge(source=0, target=1, type=0), Edge(source=2, target=3, type=0), Edge
(source=4, target=5, type=0), Edge(source=5, target=6, type=0), Edge(source=6, target=7, type=0), Edge(source=8, target=9, type=0), Edge(source=9, target=10, type=0), Edge(source=
10, target=11, type=0), Edge(source=12, target=13, type=0), Edge(source=14, target=15, type=0), Edge(source=8, target=17, type=0), Edge(source=4, target=19, type=0), Edge(source=2
0, target=1, type=0), Edge(source=18, target=6, type=0), Edge(source=16, target=11, type=0), Edge(source=1, target=2, type=1), Edge(source=3, target=4, type=1), Edge(source=7, tar
get=8, type=1), Edge(source=11, target=12, type=1), Edge(source=13, target=14, type=1), Edge(source=15, target=16, type=1), Edge(source=17, target=18, type=1), Edge(source=19, tar
get=20, type=1)], num_edge_types=3, node_features=[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.
0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 35.452999114990234, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0
.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0
.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.0109996
7956543, 4.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0
, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0
, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.
0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 14.006999969482422,
 3.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0
.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0
.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0
.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 15.99899959564209, 2.0, 0.0
, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 
0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.
0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 
0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0,
 0.0, 0.0, 12.01099967956543, 4.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.
0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 1.0, 1.0, 1.
0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0
.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0
, 14.006999969482422, 3.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 14.006999969482422, 3.0, 0.0, 1.0, 1.0, 0.0,
 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0
.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0
.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 12.01099967956543, 4.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], graph_properties=OrderedDict([('sa_s
core', 1.822853297851525), ('clogp', 3.5588000000000015), ('mol_weight', 299.082539748), ('qed', 0.723011946080414), ('bertz', 695.0560894658073)]), node_types=['Cl', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'N', 'C', 'C'], smiles_string='Clc1ccc(Cn2cc(COc3ccccc3)nn2)cc1', motifs=[MotifAnnotation(motif_type='C1=CC=CC=C1', atoms=[MotifAtomAnnotation(atom_id=1, symmetry_class_id=0), MotifAtomAnnotation(atom_id=2, symmetry_class_id=0), MotifAtomAnnotation(atom_id=3, symmetry_class_id=0), MotifAtomAnnotation(atom_id=4, symmetry_class_id=0), MotifAtomAnnotation(atom_id=19, symmetry_class_id=0), MotifAtomAnnotation(atom_id=20, symmetry_class_id=0)]), MotifAnnotation(motif_type='C1=CNN=N1', atoms=[MotifAtomAnnotation(atom_id=6, symmetry_class_id=2), MotifAtomAnnotation(atom_id=7, symmetry_class_id=0), MotifAtomAnnotation(atom_id=8, symmetry_class_id=1), MotifAtomAnnotation(atom_id=17, symmetry_class_id=3), MotifAtomAnnotation(atom_id=18, symmetry_class_id=4)]), MotifAnnotation(motif_type='C1=CC=CC=C1', atoms=[MotifAtomAnnotation(atom_id=11, symmetry_class_id=0), MotifAtomAnnotation(atom_id=12, symmetry_class_id=0), MotifAtomAnnotation(atom_id=13, symmetry_class_id=0), MotifAtomAnnotation(atom_id=14, symmetry_class_id=0), MotifAtomAnnotation(atom_id=15, symmetry_class_id=0), MotifAtomAnnotation(atom_id=16, symmetry_class_id=0)])], node_categorical_features=[134, 0, 0, 0, 0, 129, 48, 48, 48, 129, 132, 0, 0, 0, 0, 0, 0, 48, 48, 0, 0], node_categorical_num_classes=166, mol=None).Error message was: module 'numpy' has no attribute 'bool'.

**Comment by ZhouChenghui** [comment]
or it looks like this:

Converting graph sample for CCCN1C(=O)c2ccc(C(=O)Nc3cc(C(=O)O)cc(C(=O)O)c3)cc2C1=O failed - aborting!

**Comment by kmaziarz** [comment]
Ah, so the key bit is
```
Error message was: module 'numpy' has no attribute 'bool'.
```
It seems doing things like `numpy.bool` was deprecated, and then got removed in `1.24`. I'll have to fix this, but in the meantime, maybe you can downgrade `numpy` to `<1.24` (e.g. `1.23.1`) and try again?

**Comment by ZhouChenghui** [comment]
I think numpy 1.23.1 still doesn't have  numpy.bool. even 1.20.3 doesn't have numpy.bool and I cannot downgrade the numpy package any further.

**Comment by ZhouChenghui** [comment]
Yes, you are right. Sorry about that. It's just a deprecation warning, so the preprocessing seems to be working as it should now. I will update you later if there's anything else comes up.Thanks a lot!

**Comment by ZhouChenghui** [comment]
Hey, just an update, I don't have any issue with training either anymore. Everything is good now. However, I have one last small question, what is the flag one can use to specify the directory for the trained model during training? I can't seem to find it... Thanks!

**Comment by kmaziarz** [comment]
> what is the flag one can use to specify the directory for the trained model during training?

Does `--save-dir` work?

In general, you can see all the flags by running `molecule_generation train -h` (assuming you installed the package via `pip`, either in editable mode or from PyPI).

**Comment by ZhouChenghui** [comment]
Yep, thank you very much!

**Comment by kmaziarz** [comment]
No worries!

(By the way, I am now updating the `numpy`-related types, so the newest code on `main` should soon work also with `1.24.0`)
