### ISSUE TITLE
Large amount of error messages when using decode

### ISSUE THREAD

**Issue by peetceenatoo** [microsoft/molecule-generation#57]
My script works, but a large amount of error messages is shown:

"RDKit runtime error on base molecule, with message:
unsupported operand type(s) for -: '_vectclass std::vector<int,class std::allocator<int> >' and '_vectclass std::vector<int,class std::allocator<int> >'"

"WARNING:tensorflow:5 out of the last 5 calls to <function MLP.call at 0x00000232D2F44D30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details."

and

"WARNING:tensorflow:6 out of the last 6 calls to <function MLP.call at 0x00000232D2F44EE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details."

Decoding 20 embeddings arrays I get more than 700 rows of errors. Then it surprisingly prints the 20 molecules, but this wall of errors is shown. I would like my scripts to not trigger errors.

**Comment by peetceenatoo** [comment]
@kmaziarz I am using `tensorflow 2.12.0` and `rdkit 2022.9.5`

**Comment by peetceenatoo** [comment]
@kmaziarz try seeing at row 47 in the file `topology_features.py` in Chem folder, I believe the substraction between the two verctors should be a substraction between their lengths.

**Comment by kmaziarz** [comment]
Should be fixed now on `main` (soon-to-be-released as `0.4.0` on pypi).

> Decoding 20 embeddings arrays I get more than 700 rows of errors. Then it surprisingly prints the 20 molecules, but this wall of errors is shown.

Before the fix, every attempt to compute the topology features (which happens a lot, pretty much every decoding step) would fail. The code is set up to be robust to random failures from `rdkit`, so when trying to compute these features fails, it just uses an all-zeros vector instead. Empirically, MoLeR doesn't put too much weight on the topology features, and so even when it falls back to using an all-zeros vector, in most cases the decoded molecule is the same, but sometimes it's a bit different. Thus, while the model may continue to give reasonable samples before the fix, please still update to the newest version.
