### ISSUE TITLE
preprocess need too many time AND how use my csv to generate  the train.smiles and valid.smiles

### ISSUE THREAD

**Issue by yuzhou2333** [microsoft/molecule-generation#66]
![image](https://github.com/microsoft/molecule-generation/assets/74141246/ec0a94f1-e762-44f4-8f70-b4bec49cb636)
i use the molecule_generation preprocess ./mol ./output ./trace.

but it takes 16 hours ,but just for write the metadata.pkl.gz for 2%,in the paper i see just use one day for K80,i use the 3090,because the V100's 24G memory is small,what's the reason,how can i decrease the time consumption.

And another question,How can i use my train.csv and valid.cvs(which include 4,000,000smiles)to generate the train.smiles and valid.smiles,thanks~

**Comment by yuzhou2333** [comment]
> > GPU 类型如何影响预处理时间？
> 
> GPU 类型（或缺少 GPU）不应发挥作用，在预处理过程中不使用 GPU。起作用的是 CPU 内核的数量和可用 RAM 的数量。您有多少个 CPU 内核和 RAM？我们尝试[在这里](https://github.com/microsoft/molecule-generation/blob/a9a3fc93a99cfdc8a59cc567a56fd56b1fc2f689/molecule_generation/cli/preprocess.py#L168)自动确定最佳进程数，在此函数结束时打印出来以查看推断的内容可能会很有趣。最后，您可以尝试直接传递以增加/减少使用的进程数。`default_num_processes``--num-processes`
> 
> > 如何生成文件？`*.smiles`
> 
> 假定这些文件只是 SMILES 的普通列表，每行一个 SMILES。如果你有一个文件，那么我会假设该文件的一列是 SMILES 本身;然后，您可以提取该列并将其保存在一个文本文件中，每行一个 SMILES。`*.csv`

Thank u ,it's very useful.my CPU is 15 vCPU AMD EPYC 7552 48-Core Processor,and my RAM is 80G.I use the default command (molecule_generation preprocess ./mol ./output ./trace).i use ur dataset and preprocess it.when it comes to 3% as the above,it shows broken pipe.I think maybe it's because no more RAM to write metadata.I'll check the num-process tomorrow.Thank you very much,it helps a lot!!
i figure it out about how to generate the smiles,thanks a lot,when i preprocess 4,000,000 train smiles,the problem is that i don't have too much RAM,so i can't run it.I'll try use less data.
Thank you,Have a great day~~

**Comment by yuzhou2333** [comment]
> > GPU 类型如何影响预处理时间？
> 
> GPU 类型（或缺少 GPU）不应发挥作用，在预处理过程中不使用 GPU。起作用的是 CPU 内核的数量和可用 RAM 的数量。您有多少个 CPU 内核和 RAM？我们尝试[在这里](https://github.com/microsoft/molecule-generation/blob/a9a3fc93a99cfdc8a59cc567a56fd56b1fc2f689/molecule_generation/cli/preprocess.py#L168)自动确定最佳进程数，在此函数结束时打印出来以查看推断的内容可能会很有趣。最后，您可以尝试直接传递以增加/减少使用的进程数。`default_num_processes``--num-processes`
> 
> > 如何生成文件？`*.smiles`
> 
> 假定这些文件只是 SMILES 的普通列表，每行一个 SMILES。如果你有一个文件，那么我会假设该文件的一列是 SMILES 本身;然后，您可以提取该列并将其保存在一个文本文件中，每行一个 SMILES。`*.csv`


![image](https://github.com/microsoft/molecule-generation/assets/74141246/e01dd9bf-878a-4616-838c-5e8767c36de5)
![image](https://github.com/microsoft/molecule-generation/assets/74141246/1a437362-a4d2-48d7-acc1-c18dc3c0a8e4)

When I run this code again ,the default_num_processes is 197,when it comes to the part of training the trace,the speed is slow down to 2it/s,
this is the CPU using and the RAM using:
![image](https://github.com/microsoft/molecule-generation/assets/74141246/95f48928-b07b-484e-9e96-76476cb11616)
![image](https://github.com/microsoft/molecule-generation/assets/74141246/b46b80ab-1f81-4e8f-ab38-63f1ab65d802)

so i'm confused ,how can i solve this problem?

**Comment by kmaziarz** [comment]
> default_num_processes is 197

That's weird, sounds way too high. Maybe just set `--num-processes 8` and rerun? If that helps and you don't run out of RAM then you can try increasing that a bit and see if it gets faster, but certainly not up to 100+.

**Comment by yuzhou2333** [comment]
> > default_num_processes is 197
> 
> That's weird, sounds way too high. Maybe just set `--num-processes 8` and rerun? If that helps and you don't run out of RAM then you can try increasing that a bit and see if it gets faster, but certainly not up to 100+.

it really helps,thank you very much~~
![image](https://github.com/microsoft/molecule-generation/assets/74141246/9a9a8114-6373-4482-a983-5aaf3d914fea)
