### ISSUE TITLE
advices of the evaluation options defined by sklearn.metrics

### ISSUE THREAD

**Issue by linjing-lab** [microsoft/molecule-generation#71]
I got some experience about designing model-based algorithm, like the frequently used MLP. I designed a pipeline when I extracted from any resources, like numpy.ndarray, and the most important thing is to unify the memory format to the foundation format which same as the models taken by a released package. As molecule_generation takes tensorflow as the main runtime, and I recommend if there exists a compatible package with the same effect of sklearn.metrics while reduce the hassle of format conversion (tf.Tensor → numpy.ndarray).

https://github.com/microsoft/molecule-generation/blob/e7e9e38479f8c4ef1d39e997ed9571d263d98e35/molecule_generation/utils/property_models.py#L177-L181

These are all equivalent forms. If the combined transformer module can generalize high-dimensional feature datasets, then these evaluations are an objective state reflected by the machine. These evaluation metrics are returned by sklearn.metrics, not by monitoring models using the APIs from tensorflow, like `tf.callbacks.ModelCheckpoint`, `tf.callbacks.EarlyStopping`, and `tf.callbacks.CSVLogger`.

**Comment by kmaziarz** [comment]
Thanks for these suggestions. The package is currently mostly in a bugfix/maintenance mode, and we have no bandwidth to refactor the internals if not necessary, but we'll keep your comment in mind.
